"""sync_face_embeddings_columns

Revision ID: b9a98c1685f5
Revises: 010_add_users_auth
Create Date: 2026-02-02 23:35:08.971421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9a98c1685f5'
down_revision: Union[str, None] = '010_add_users_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    inspector = sa.inspect(bind)

    def _has_column(table: str, column: str) -> bool:
        return any(c["name"] == column for c in inspector.get_columns(table))

    # Postgres-only: JSONB -> JSON cast. SQLite stores JSON as TEXT either way,
    # so no work is required there.
    if not is_sqlite:
        op.alter_column('assets', 'reference_image_meta',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   type_=sa.JSON(),
                   existing_nullable=True)

    # Postgres-only: drop auto-named indexes / FKs that only exist under
    # Postgres' naming. On SQLite these names were never created, so the
    # drops would fail. The subsequent create_foreign_key calls likewise
    # only make sense on Postgres (SQLite tables already declare these FKs
    # inline at CREATE TABLE time, and ALTER TABLE ADD CONSTRAINT is not
    # supported by SQLite).
    if not is_sqlite:
        op.drop_index(op.f('ix_conversation_actions_conversation_id'), table_name='conversation_actions')
        op.drop_index(op.f('ix_conversation_actions_created_at'), table_name='conversation_actions')
        op.drop_index(op.f('ix_conversation_actions_job_id'), table_name='conversation_actions')
        op.drop_index(op.f('ix_conversation_actions_message_id'), table_name='conversation_actions')
        op.drop_index(op.f('ix_conversation_actions_status'), table_name='conversation_actions')
        op.drop_constraint(op.f('conversation_actions_message_id_fkey'), 'conversation_actions', type_='foreignkey')
        op.drop_constraint(op.f('conversation_actions_job_id_fkey'), 'conversation_actions', type_='foreignkey')
        op.drop_constraint(op.f('conversation_actions_conversation_id_fkey'), 'conversation_actions', type_='foreignkey')
        op.create_foreign_key(None, 'conversation_actions', 'conversation_messages', ['message_id'], ['id'])
        op.create_foreign_key(None, 'conversation_actions', 'jobs', ['job_id'], ['id'])
        op.create_foreign_key(None, 'conversation_actions', 'conversations', ['conversation_id'], ['id'])

    # NOT NULL tightening: meaningful on both dialects. Use batch_alter_table
    # so SQLite can recreate the table.
    with op.batch_alter_table('conversation_messages') as batch_op:
        batch_op.alter_column('tokens_used',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    if not is_sqlite:
        op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
        op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
        op.drop_index(op.f('ix_conversation_messages_role'), table_name='conversation_messages')
        op.drop_constraint(op.f('conversation_messages_conversation_id_fkey'), 'conversation_messages', type_='foreignkey')
        op.create_foreign_key(None, 'conversation_messages', 'conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('conversations') as batch_op:
        batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)

    if not is_sqlite:
        op.drop_index(op.f('ix_conversations_chapter_id'), table_name='conversations')
        op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
        op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
        op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
        op.drop_constraint(op.f('conversations_chapter_id_fkey'), 'conversations', type_='foreignkey')
        op.drop_constraint(op.f('conversations_project_id_fkey'), 'conversations', type_='foreignkey')
        op.create_foreign_key(None, 'conversations', 'chapters', ['chapter_id'], ['id'])
        op.create_foreign_key(None, 'conversations', 'projects', ['project_id'], ['id'])

    # face_embeddings: this migration was auto-generated against a DB whose
    # face_embeddings table already had `canonical_id`, `model_name`,
    # `model_hash`, and `dim` columns (likely from a prior `create_all`).
    # No earlier migration adds them, so on a fresh DB we need to add them
    # before the alter_column / FK calls below would have anything to
    # operate on. Guard each step with an existence check so the migration
    # is safe both on a fresh DB and on legacy DBs that already have them.
    fe_columns_to_add = []
    if not _has_column('face_embeddings', 'canonical_id'):
        fe_columns_to_add.append(
            sa.Column('canonical_id', sa.String(36), nullable=True)
        )
    if not _has_column('face_embeddings', 'model_name'):
        fe_columns_to_add.append(
            sa.Column('model_name', sa.String(100), nullable=True,
                      server_default='buffalo_l')
        )
    if not _has_column('face_embeddings', 'model_hash'):
        fe_columns_to_add.append(
            sa.Column('model_hash', sa.String(64), nullable=True)
        )
    dim_existed = _has_column('face_embeddings', 'dim')
    if not dim_existed:
        fe_columns_to_add.append(
            sa.Column('dim', sa.Integer(), nullable=False,
                      server_default=sa.text('512'))
        )

    if fe_columns_to_add:
        with op.batch_alter_table('face_embeddings') as batch_op:
            for col in fe_columns_to_add:
                batch_op.add_column(col)

    # If `dim` already existed, tighten its nullability to NOT NULL (the
    # original intent of this migration). If we just added it as NOT NULL
    # above, this is a no-op.
    if dim_existed:
        with op.batch_alter_table('face_embeddings') as batch_op:
            batch_op.alter_column('dim',
                       existing_type=sa.INTEGER(),
                       nullable=False,
                       existing_server_default=sa.text('512'))

    if not is_sqlite:
        op.create_foreign_key(None, 'face_embeddings', 'character_canonicals', ['canonical_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    if not is_sqlite:
        op.drop_constraint(None, 'face_embeddings', type_='foreignkey')

    with op.batch_alter_table('face_embeddings') as batch_op:
        batch_op.alter_column('dim',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text('512'))

    if not is_sqlite:
        op.drop_constraint(None, 'conversations', type_='foreignkey')
        op.drop_constraint(None, 'conversations', type_='foreignkey')
        op.create_foreign_key(op.f('conversations_project_id_fkey'), 'conversations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(op.f('conversations_chapter_id_fkey'), 'conversations', 'chapters', ['chapter_id'], ['id'], ondelete='SET NULL')
        op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
        op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
        op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
        op.create_index(op.f('ix_conversations_chapter_id'), 'conversations', ['chapter_id'], unique=False)

    with op.batch_alter_table('conversations') as batch_op:
        batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)

    if not is_sqlite:
        op.drop_constraint(None, 'conversation_messages', type_='foreignkey')
        op.create_foreign_key(op.f('conversation_messages_conversation_id_fkey'), 'conversation_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
        op.create_index(op.f('ix_conversation_messages_role'), 'conversation_messages', ['role'], unique=False)
        op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
        op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)

    with op.batch_alter_table('conversation_messages') as batch_op:
        batch_op.alter_column('tokens_used',
                   existing_type=sa.INTEGER(),
                   nullable=True)

    if not is_sqlite:
        op.drop_constraint(None, 'conversation_actions', type_='foreignkey')
        op.drop_constraint(None, 'conversation_actions', type_='foreignkey')
        op.drop_constraint(None, 'conversation_actions', type_='foreignkey')
        op.create_foreign_key(op.f('conversation_actions_conversation_id_fkey'), 'conversation_actions', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(op.f('conversation_actions_job_id_fkey'), 'conversation_actions', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
        op.create_foreign_key(op.f('conversation_actions_message_id_fkey'), 'conversation_actions', 'conversation_messages', ['message_id'], ['id'], ondelete='CASCADE')
        op.create_index(op.f('ix_conversation_actions_status'), 'conversation_actions', ['status'], unique=False)
        op.create_index(op.f('ix_conversation_actions_message_id'), 'conversation_actions', ['message_id'], unique=False)
        op.create_index(op.f('ix_conversation_actions_job_id'), 'conversation_actions', ['job_id'], unique=False)
        op.create_index(op.f('ix_conversation_actions_created_at'), 'conversation_actions', ['created_at'], unique=False)
        op.create_index(op.f('ix_conversation_actions_conversation_id'), 'conversation_actions', ['conversation_id'], unique=False)
        op.alter_column('assets', 'reference_image_meta',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
    # ### end Alembic commands ###
