"""sync_face_embeddings_columns

Revision ID: b9a98c1685f5
Revises: 010_add_users_auth
Create Date: 2026-02-02 23:35:08.971421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9a98c1685f5'
down_revision: Union[str, None] = '010_add_users_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'reference_image_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_conversation_actions_conversation_id'), table_name='conversation_actions')
    op.drop_index(op.f('ix_conversation_actions_created_at'), table_name='conversation_actions')
    op.drop_index(op.f('ix_conversation_actions_job_id'), table_name='conversation_actions')
    op.drop_index(op.f('ix_conversation_actions_message_id'), table_name='conversation_actions')
    op.drop_index(op.f('ix_conversation_actions_status'), table_name='conversation_actions')
    op.drop_constraint(op.f('conversation_actions_message_id_fkey'), 'conversation_actions', type_='foreignkey')
    op.drop_constraint(op.f('conversation_actions_job_id_fkey'), 'conversation_actions', type_='foreignkey')
    op.drop_constraint(op.f('conversation_actions_conversation_id_fkey'), 'conversation_actions', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_actions', 'conversation_messages', ['message_id'], ['id'])
    op.create_foreign_key(None, 'conversation_actions', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'conversation_actions', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('conversation_messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_role'), table_name='conversation_messages')
    op.drop_constraint(op.f('conversation_messages_conversation_id_fkey'), 'conversation_messages', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_conversations_chapter_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_constraint(op.f('conversations_chapter_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_project_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'chapters', ['chapter_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'projects', ['project_id'], ['id'])
    op.alter_column('face_embeddings', 'dim',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('512'))
    op.create_foreign_key(None, 'face_embeddings', 'character_canonicals', ['canonical_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'face_embeddings', type_='foreignkey')
    op.alter_column('face_embeddings', 'dim',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('512'))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_project_id_fkey'), 'conversations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversations_chapter_id_fkey'), 'conversations', 'chapters', ['chapter_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_chapter_id'), 'conversations', ['chapter_id'], unique=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'conversation_messages', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_messages_conversation_id_fkey'), 'conversation_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_messages_role'), 'conversation_messages', ['role'], unique=False)
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.alter_column('conversation_messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'conversation_actions', type_='foreignkey')
    op.drop_constraint(None, 'conversation_actions', type_='foreignkey')
    op.drop_constraint(None, 'conversation_actions', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_actions_conversation_id_fkey'), 'conversation_actions', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversation_actions_job_id_fkey'), 'conversation_actions', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('conversation_actions_message_id_fkey'), 'conversation_actions', 'conversation_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_actions_status'), 'conversation_actions', ['status'], unique=False)
    op.create_index(op.f('ix_conversation_actions_message_id'), 'conversation_actions', ['message_id'], unique=False)
    op.create_index(op.f('ix_conversation_actions_job_id'), 'conversation_actions', ['job_id'], unique=False)
    op.create_index(op.f('ix_conversation_actions_created_at'), 'conversation_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_actions_conversation_id'), 'conversation_actions', ['conversation_id'], unique=False)
    op.alter_column('assets', 'reference_image_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
